on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install --prefix "my-react-app - Bertie"
      
    - name: Build
      run: CI=false npm run build --prefix "my-react-app - Bertie"

    - name: ZIP build directory
      run: tar -zcvf build.tar.gz -C "my-react-app - Bertie/build" .

    - name: Upload build.tar.gz as artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ./build.tar.gz

    - name: List repository files
      run: ls -la

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact

    - name: List files after downloading artifact
      run: ls -la

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bertie-porfolio'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6607B78F7F024E418445247EF4E69612 }}
        package: ./build.tar.gz
